-------------------------------------------------------------------------------
-- SCRIPT 1 — SCHEMA BITEMPORALĂ (tabele + constrângeri + triggere TT)
-- Oracle 21c+ | folosește IDENTITY | PERIOD FOR valid_period pe toate tabelele
-------------------------------------------------------------------------------
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

-------------------------------------------------------------------------------
-- 0) PALETĂ COMUNĂ: câmpuri bitemporale
--    - valid_start, valid_end       -> VALID TIME (realitatea)
--    - transaction_start, _end      -> TRANSACTION TIME (când a știut sistemul)
--    - PERIOD FOR valid_period(...) -> anunță Oracle că intervalul e “temporal”
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
-- 1) CLUBS
-------------------------------------------------------------------------------
CREATE TABLE clubs (
  club_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name               VARCHAR2(200) NOT NULL UNIQUE,
  country            CHAR(2) NOT NULL,
  valid_start        TIMESTAMP NOT NULL,
  valid_end          TIMESTAMP NOT NULL,
  transaction_start  TIMESTAMP NOT NULL,
  transaction_end    TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT clubs_ck_valid CHECK (valid_end > valid_start),
  CONSTRAINT clubs_ck_tx    CHECK (transaction_end > transaction_start)
);

-------------------------------------------------------------------------------
-- 2) COACHES
-------------------------------------------------------------------------------
CREATE TABLE coaches (
  coach_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name          VARCHAR2(200) NOT NULL,
  email              VARCHAR2(200),
  valid_start        TIMESTAMP NOT NULL,
  valid_end          TIMESTAMP NOT NULL,
  transaction_start  TIMESTAMP NOT NULL,
  transaction_end    TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT coaches_ck_valid CHECK (valid_end > valid_start),
  CONSTRAINT coaches_ck_tx    CHECK (transaction_end > transaction_start)
);

-------------------------------------------------------------------------------
-- 3) CLUB_COACHES (istoric antrenori la club)
-------------------------------------------------------------------------------
CREATE TABLE club_coaches (
  club_coach_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id            NUMBER NOT NULL REFERENCES clubs(club_id),
  coach_id           NUMBER NOT NULL REFERENCES coaches(coach_id),
  role               VARCHAR2(50) DEFAULT 'head' NOT NULL,
  valid_start        TIMESTAMP NOT NULL,
  valid_end          TIMESTAMP NOT NULL,
  transaction_start  TIMESTAMP NOT NULL,
  transaction_end    TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT club_coaches_ck_role  CHECK (role IN ('head','assistant','fitness')),
  CONSTRAINT club_coaches_ck_valid CHECK (valid_end > valid_start),
  CONSTRAINT club_coaches_ck_tx    CHECK (transaction_end > transaction_start)
);

-------------------------------------------------------------------------------
-- 4) PLAYERS
-------------------------------------------------------------------------------
CREATE TABLE players (
  player_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name          VARCHAR2(200) NOT NULL,
  dob                DATE,
  nationality        CHAR(2),
  primary_position   VARCHAR2(2)
    CHECK (primary_position IN ('GK','DF','MF','FW')),
  valid_start        TIMESTAMP NOT NULL,
  valid_end          TIMESTAMP NOT NULL,
  transaction_start  TIMESTAMP NOT NULL,
  transaction_end    TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT players_ck_valid CHECK (valid_end > valid_start),
  CONSTRAINT players_ck_tx    CHECK (transaction_end > transaction_start)
);

-------------------------------------------------------------------------------
-- 5) CONTRACTS (istoric contracte jucător–club)
-------------------------------------------------------------------------------
CREATE TABLE contracts (
  contract_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id          NUMBER NOT NULL REFERENCES players(player_id),
  club_id            NUMBER NOT NULL REFERENCES clubs(club_id),
  salary             NUMBER(12,2),
  shirt_number       NUMBER,
  valid_start        TIMESTAMP NOT NULL,
  valid_end          TIMESTAMP NOT NULL,
  transaction_start  TIMESTAMP NOT NULL,
  transaction_end    TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT contracts_ck_valid CHECK (valid_end > valid_start),
  CONSTRAINT contracts_ck_tx    CHECK (transaction_end > transaction_start)
);

-------------------------------------------------------------------------------
-- 6) COMPETITIONS
-------------------------------------------------------------------------------
CREATE TABLE competitions (
  competition_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code               VARCHAR2(50) NOT NULL,
  name               VARCHAR2(200) NOT NULL,
  country            CHAR(2) NOT NULL,
  season             VARCHAR2(20) NOT NULL,
  valid_start        TIMESTAMP NOT NULL,
  valid_end          TIMESTAMP NOT NULL,
  transaction_start  TIMESTAMP NOT NULL,
  transaction_end    TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT competitions_uq UNIQUE (code, season),
  CONSTRAINT competitions_ck_valid CHECK (valid_end > valid_start),
  CONSTRAINT competitions_ck_tx    CHECK (transaction_end > transaction_start)
);

-------------------------------------------------------------------------------
-- 7) MATCHES
-------------------------------------------------------------------------------
CREATE TABLE matches (
  match_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competition_id     NUMBER NOT NULL REFERENCES competitions(competition_id),
  match_date         TIMESTAMP NOT NULL,
  home_club_id       NUMBER NOT NULL REFERENCES clubs(club_id),
  away_club_id       NUMBER NOT NULL REFERENCES clubs(club_id),
  venue              VARCHAR2(200),
  valid_start        TIMESTAMP NOT NULL,
  valid_end          TIMESTAMP NOT NULL,
  transaction_start  TIMESTAMP NOT NULL,
  transaction_end    TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT matches_ck_teams CHECK (home_club_id <> away_club_id),
  CONSTRAINT matches_uq UNIQUE (competition_id, match_date, home_club_id, away_club_id),
  CONSTRAINT matches_ck_valid CHECK (valid_end > valid_start),
  CONSTRAINT matches_ck_tx    CHECK (transaction_end > transaction_start)
);

-------------------------------------------------------------------------------
-- 8) REGISTRATIONS (înscrieri în competiții)
-------------------------------------------------------------------------------
CREATE TABLE registrations (
  registration_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id          NUMBER NOT NULL REFERENCES players(player_id),
  club_id            NUMBER NOT NULL REFERENCES clubs(club_id),
  competition_id     NUMBER NOT NULL REFERENCES competitions(competition_id),
  status             VARCHAR2(20)
    CHECK (status IN ('registered','loaned_out','deregistered')) NOT NULL,
  valid_start        TIMESTAMP NOT NULL,
  valid_end          TIMESTAMP NOT NULL,
  transaction_start  TIMESTAMP NOT NULL,
  transaction_end    TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT registrations_ck_valid CHECK (valid_end > valid_start),
  CONSTRAINT registrations_ck_tx    CHECK (transaction_end > transaction_start)
);

-------------------------------------------------------------------------------
-- 9) APPEARANCES (aparitii la meci)
-------------------------------------------------------------------------------
CREATE TABLE appearances (
  appearance_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id           NUMBER NOT NULL REFERENCES matches(match_id),
  player_id          NUMBER NOT NULL REFERENCES players(player_id),
  club_id            NUMBER NOT NULL REFERENCES clubs(club_id),
  role               VARCHAR2(10)
    CHECK (role IN ('starter','sub','unused')) NOT NULL,
  minutes_played     NUMBER,
  goals              NUMBER DEFAULT 0,
  assists            NUMBER DEFAULT 0,
  yellow_cards       NUMBER DEFAULT 0,
  red_cards          NUMBER DEFAULT 0,
  valid_start        TIMESTAMP NOT NULL,
  valid_end          TIMESTAMP NOT NULL,
  transaction_start  TIMESTAMP NOT NULL,
  transaction_end    TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT appearances_ck_min   CHECK (minutes_played BETWEEN 0 AND 120),
  CONSTRAINT appearances_ck_cards CHECK (yellow_cards BETWEEN 0 AND 2 AND red_cards BETWEEN 0 AND 1),
  CONSTRAINT appearances_ck_valid CHECK (valid_end > valid_start),
  CONSTRAINT appearances_ck_tx    CHECK (transaction_end > transaction_start)
);

-------------------------------------------------------------------------------
-- 10) CLUB_DEPARTMENTS (Senior, U21 etc.)
-------------------------------------------------------------------------------
CREATE TABLE club_departments (
  department_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id            NUMBER NOT NULL REFERENCES clubs(club_id),
  name               VARCHAR2(80) NOT NULL,
  valid_start        TIMESTAMP NOT NULL,
  valid_end          TIMESTAMP NOT NULL,
  transaction_start  TIMESTAMP NOT NULL,
  transaction_end    TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT uq_club_dept UNIQUE (club_id, name, valid_start),
  CONSTRAINT club_dept_ck_valid CHECK (valid_end > valid_start),
  CONSTRAINT club_dept_ck_tx    CHECK (transaction_end > transaction_start)
);

-------------------------------------------------------------------------------
-- 11) COACH_DEPARTMENT_ROLES (head coach ↔️ Senior dept)
-------------------------------------------------------------------------------
CREATE TABLE coach_department_roles (
  coach_dept_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id      NUMBER NOT NULL REFERENCES club_departments(department_id),
  coach_id           NUMBER NOT NULL REFERENCES coaches(coach_id),
  role               VARCHAR2(80) DEFAULT 'head' NOT NULL,
  valid_start        TIMESTAMP NOT NULL,
  valid_end          TIMESTAMP NOT NULL,
  transaction_start  TIMESTAMP NOT NULL,
  transaction_end    TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT cdr_ck_valid CHECK (valid_end > valid_start),
  CONSTRAINT cdr_ck_tx    CHECK (transaction_end > transaction_start)
);

-------------------------------------------------------------------------------
-- 12) PLAYER_DEPARTMENT_ASSIGNMENTS (U21/Senior în timp)
-------------------------------------------------------------------------------
CREATE TABLE player_department_assignments (
  player_dept_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id          NUMBER NOT NULL REFERENCES players(player_id),
  department_id      NUMBER NOT NULL REFERENCES club_departments(department_id),
  note               VARCHAR2(80),
  valid_start        TIMESTAMP NOT NULL,
  valid_end          TIMESTAMP NOT NULL,
  transaction_start  TIMESTAMP NOT NULL,
  transaction_end    TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT pda_ck_valid CHECK (valid_end > valid_start),
  CONSTRAINT pda_ck_tx    CHECK (transaction_end > transaction_start)
);

-------------------------------------------------------------------------------
-- INDEXURI pe FK (performanță)
-------------------------------------------------------------------------------
CREATE INDEX ix_cc_club    ON club_coaches(club_id);
CREATE INDEX ix_cc_coach   ON club_coaches(coach_id);

CREATE INDEX ix_ct_player  ON contracts(player_id);
CREATE INDEX ix_ct_club    ON contracts(club_id);

CREATE INDEX ix_rg_player  ON registrations(player_id);
CREATE INDEX ix_rg_club    ON registrations(club_id);
CREATE INDEX ix_rg_comp    ON registrations(competition_id);

CREATE INDEX ix_mt_comp    ON matches(competition_id);
CREATE INDEX ix_mt_home    ON matches(home_club_id);
CREATE INDEX ix_mt_away    ON matches(away_club_id);

CREATE INDEX ix_ap_match   ON appearances(match_id);
CREATE INDEX ix_ap_player  ON appearances(player_id);
CREATE INDEX ix_ap_club    ON appearances(club_id);

CREATE INDEX ix_cd_club    ON club_departments(club_id);
CREATE INDEX ix_cdr_dept   ON coach_department_roles(department_id);
CREATE INDEX ix_cdr_coach  ON coach_department_roles(coach_id);
CREATE INDEX ix_pda_player ON player_department_assignments(player_id);
CREATE INDEX ix_pda_dept   ON player_department_assignments(department_id);

-------------------------------------------------------------------------------
-- TRIGGERE: inițializează Transaction Time la INSERT (TT open-ended)
-- Rule: dacă lipsește, setăm transaction_start = SYSTIMESTAMP
--       și transaction_end   = 9999-12-31 23:59:59
-------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER set_tx_times_clubs
BEFORE INSERT ON clubs FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end,
    TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_coaches
BEFORE INSERT ON coaches FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end,
    TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_club_coaches
BEFORE INSERT ON club_coaches FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end,
    TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_players
BEFORE INSERT ON players FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end,
    TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_contracts
BEFORE INSERT ON contracts FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end,
    TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_competitions
BEFORE INSERT ON competitions FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end,
    TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_matches
BEFORE INSERT ON matches FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end,
    TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_registrations
BEFORE INSERT ON registrations FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end,
    TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_appearances
BEFORE INSERT ON appearances FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end,
    TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_club_departments
BEFORE INSERT ON club_departments FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end,
    TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_coach_dept_roles
BEFORE INSERT ON coach_department_roles FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end,
    TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_player_dept_assign
BEFORE INSERT ON player_department_assignments FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end,
    TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

-------------------------------------------------------------------------------
-- TRIGGERE “FORBID” — blochează UPDATE/DELETE direct pe faptele cu istoric
-- Folosește doar procedurile version_* pentru a păstra lanțul tranzacțional
-------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER forbid_ud_contracts
BEFORE UPDATE OR DELETE ON contracts
BEGIN
  RAISE_APPLICATION_ERROR(-20030,
    'Nu se permite UPDATE/DELETE direct pe CONTRACTS. Foloseste version_contract().');
END;
/

CREATE OR REPLACE TRIGGER forbid_ud_registrations
BEFORE UPDATE OR DELETE ON registrations
BEGIN
  RAISE_APPLICATION_ERROR(-20031,
    'Nu se permite UPDATE/DELETE direct pe REGISTRATIONS. Foloseste version_registration().');
END;
/

CREATE OR REPLACE TRIGGER forbid_ud_appearances
BEFORE UPDATE OR DELETE ON appearances
BEGIN
  RAISE_APPLICATION_ERROR(-20032,
    'Nu se permite UPDATE/DELETE direct pe APPEARANCES. Foloseste version_appearance().');
END;
/

-------------------------------------------------------------------------------
-- SFÂRȘIT SCRIPT 1
-------------------------------------------------------------------------------

ALTER SESSION SET NLS_TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS';

--BEGIN
--  FOR t IN (SELECT trigger_name FROM user_triggers WHERE trigger_name IN (
--    'FORBID_UD_APPEARANCES','FORBID_UD_REGISTRATIONS','FORBID_UD_CONTRACTS','FORBID_UD_CLUB_COACHES'
--  )) LOOP
--    EXECUTE IMMEDIATE 'ALTER TRIGGER '||t.trigger_name||' DISABLE';
--  END LOOP;
--END;
--/
--
--DELETE FROM appearances;
--DELETE FROM matches;
--DELETE FROM registrations;
--DELETE FROM contracts;
--DELETE FROM club_coaches;
--DELETE FROM coaches;
--DELETE FROM competitions;
--DELETE FROM players;
--DELETE FROM clubs;
--COMMIT;
--
--BEGIN
--  FOR t IN (SELECT trigger_name FROM user_triggers WHERE trigger_name IN (
--    'FORBID_UD_APPEARANCES','FORBID_UD_REGISTRATIONS','FORBID_UD_CONTRACTS','FORBID_UD_CLUB_COACHES'
--  )) LOOP
--    EXECUTE IMMEDIATE 'ALTER TRIGGER '||t.trigger_name||' ENABLE';
--  END LOOP;
--END;
--/

-- 1) CLUBURI + COMPETIȚII (sezon 2025/26) --
INSERT INTO clubs(name,country,valid_start,valid_end,transaction_start,transaction_end)
VALUES ('FCSB','RO',TIMESTAMP '2025-07-01 00:00:00',TIMESTAMP '9999-12-31 23:59:59',SYSTIMESTAMP,TO_TIMESTAMP('9999-12-31 23:59:59'));
INSERT INTO clubs(name,country,valid_start,valid_end,transaction_start,transaction_end)
VALUES ('CFR Cluj','RO',TIMESTAMP '2025-07-01 00:00:00',TIMESTAMP '9999-12-31 23:59:59',SYSTIMESTAMP,TO_TIMESTAMP('9999-12-31 23:59:59'));
INSERT INTO clubs(name,country,valid_start,valid_end,transaction_start,transaction_end)
VALUES ('Rapid București','RO',TIMESTAMP '2025-07-01 00:00:00',TIMESTAMP '9999-12-31 23:59:59',SYSTIMESTAMP,TO_TIMESTAMP('9999-12-31 23:59:59'));
INSERT INTO clubs(name,country,valid_start,valid_end,transaction_start,transaction_end)
VALUES ('Universitatea Craiova','RO',TIMESTAMP '2025-07-01 00:00:00',TIMESTAMP '9999-12-31 23:59:59',SYSTIMESTAMP,TO_TIMESTAMP('9999-12-31 23:59:59'));
INSERT INTO clubs(name,country,valid_start,valid_end,transaction_start,transaction_end)
VALUES ('Farul Constanța','RO',TIMESTAMP '2025-07-01 00:00:00',TIMESTAMP '9999-12-31 23:59:59',SYSTIMESTAMP,TO_TIMESTAMP('9999-12-31 23:59:59'));
INSERT INTO clubs(name,country,valid_start,valid_end,transaction_start,transaction_end)
VALUES ('Dinamo București','RO',TIMESTAMP '2025-07-01 00:00:00',TIMESTAMP '9999-12-31 23:59:59',SYSTIMESTAMP,TO_TIMESTAMP('9999-12-31 23:59:59'));

INSERT INTO competitions(code,name,country,season,valid_start,valid_end,transaction_start,transaction_end)
VALUES ('L1','Liga 1','RO','2025/26',TIMESTAMP '2025-07-15 00:00:00',TIMESTAMP '9999-12-31 23:59:59',SYSTIMESTAMP,TO_TIMESTAMP('9999-12-31 23:59:59'));
INSERT INTO competitions(code,name,country,season,valid_start,valid_end,transaction_start,transaction_end)
VALUES ('CUPA','Cupa României','RO','2025/26',TIMESTAMP '2025-08-15 00:00:00',TIMESTAMP '9999-12-31 23:59:59',SYSTIMESTAMP,TO_TIMESTAMP('9999-12-31 23:59:59'));
COMMIT;

-- 2) COACHES + ISTORIC HEAD COACH PER CLUB --
BEGIN
  FOR i IN 1..6 LOOP
    INSERT INTO coaches(full_name,email,valid_start,valid_end,transaction_start,transaction_end)
    VALUES ('Coach '||i,'coach'||i||'@club.ro',
            TIMESTAMP '2025-07-01 00:00:00',TO_TIMESTAMP('9999-12-31 23:59:59'),
            SYSTIMESTAMP,TO_TIMESTAMP('9999-12-31 23:59:59'));
  END LOOP;
END;
/

DECLARE
  v_mid TIMESTAMP := TIMESTAMP '2026-02-01 00:00:00';
  PROCEDURE put_head(p_club_name VARCHAR2, p_coach_name VARCHAR2,
                     p_start TIMESTAMP, p_end TIMESTAMP) IS
  BEGIN
    INSERT INTO club_coaches(
      club_id, coach_id, role, valid_start, valid_end, transaction_start, transaction_end
    )
    VALUES (
      club_id(p_club_name),
      coach_id_by_name(p_coach_name),
      'head',
      p_start, p_end,
      SYSTIMESTAMP, TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
    );
  END;
BEGIN
  -- perioada 1
  put_head('FCSB','Coach 1',TIMESTAMP '2025-08-01 00:00:00',v_mid);
  put_head('CFR Cluj','Coach 2',TIMESTAMP '2025-08-01 00:00:00',v_mid);
  put_head('Rapid București','Coach 3',TIMESTAMP '2025-08-01 00:00:00',v_mid);
  put_head('Universitatea Craiova','Coach 4',TIMESTAMP '2025-08-01 00:00:00',v_mid);
  put_head('Farul Constanța','Coach 5',TIMESTAMP '2025-08-01 00:00:00',v_mid);
  put_head('Dinamo București','Coach 6',TIMESTAMP '2025-08-01 00:00:00',v_mid);
  -- perioada 2
  put_head('FCSB','Coach 2',v_mid,TIMESTAMP '2026-06-30 23:59:59');
  put_head('CFR Cluj','Coach 3',v_mid,TIMESTAMP '2026-06-30 23:59:59');
  put_head('Rapid București','Coach 4',v_mid,TIMESTAMP '2026-06-30 23:59:59');
  put_head('Universitatea Craiova','Coach 5',v_mid,TIMESTAMP '2026-06-30 23:59:59');
  put_head('Farul Constanța','Coach 6',v_mid,TIMESTAMP '2026-06-30 23:59:59');
  put_head('Dinamo București','Coach 1',v_mid,TIMESTAMP '2026-06-30 23:59:59');
END;
/
COMMIT;

-- 3) 150 JUCATORI (25×6) + CONTRACTE initiale --
BEGIN
  -- FCSB
  FOR i IN 1..25 LOOP
    add_player_with_contract('FCSB Player '||LPAD(i,2,'0'),
      DATE '1990-01-01' + MOD(i,9000),'RO',
      CASE MOD(i,4) WHEN 0 THEN 'GK' WHEN 1 THEN 'DF' WHEN 2 THEN 'MF' ELSE 'FW' END,
      'FCSB',120000+1000*i,10+i,
      TIMESTAMP '2025-07-15 00:00:00',TIMESTAMP '2026-06-30 23:59:59');
  END LOOP;

  -- CFR Cluj
  FOR i IN 1..25 LOOP
    add_player_with_contract('CFR Player '||LPAD(i,2,'0'),
      DATE '1990-01-01' + MOD(i+50,9000),'RO',
      CASE MOD(i+1,4) WHEN 0 THEN 'GK' WHEN 1 THEN 'DF' WHEN 2 THEN 'MF' ELSE 'FW' END,
      'CFR Cluj',115000+1000*i,20+i,
      TIMESTAMP '2025-07-20 00:00:00',TIMESTAMP '2026-06-30 23:59:59');
  END LOOP;

  -- Rapid București
  FOR i IN 1..25 LOOP
    add_player_with_contract('Rapid Player '||LPAD(i,2,'0'),
      DATE '1990-01-01' + MOD(i+100,9000),'RO',
      CASE MOD(i+2,4) WHEN 0 THEN 'GK' WHEN 1 THEN 'DF' WHEN 2 THEN 'MF' ELSE 'FW' END,
      'Rapid București',110000+900*i,30+i,
      TIMESTAMP '2025-07-20 00:00:00',TIMESTAMP '2026-06-30 23:59:59');
  END LOOP;

  -- Universitatea Craiova
  FOR i IN 1..25 LOOP
    add_player_with_contract('Craiova Player '||LPAD(i,2,'0'),
      DATE '1990-01-01' + MOD(i+150,9000),'RO',
      CASE MOD(i+3,4) WHEN 0 THEN 'GK' WHEN 1 THEN 'DF' WHEN 2 THEN 'MF' ELSE 'FW' END,
      'Universitatea Craiova',108000+900*i,40+i,
      TIMESTAMP '2025-07-20 00:00:00',TIMESTAMP '2026-06-30 23:59:59');
  END LOOP;

  -- Farul Constanța
  FOR i IN 1..25 LOOP
    add_player_with_contract('Farul Player '||LPAD(i,2,'0'),
      DATE '1990-01-01' + MOD(i+200,9000),'RO',
      CASE MOD(i,4) WHEN 0 THEN 'GK' WHEN 1 THEN 'DF' WHEN 2 THEN 'MF' ELSE 'FW' END,
      'Farul Constanța',105000+800*i,50+i,
      TIMESTAMP '2025-07-18 00:00:00',TIMESTAMP '2026-06-30 23:59:59');
  END LOOP;

  -- Dinamo București
  FOR i IN 1..25 LOOP
    add_player_with_contract('Dinamo Player '||LPAD(i,2,'0'),
      DATE '1990-01-01' + MOD(i+250,9000),'RO',
      CASE MOD(i+1,4) WHEN 0 THEN 'GK' WHEN 1 THEN 'DF' WHEN 2 THEN 'MF' ELSE 'FW' END,
      'Dinamo București',112000+950*i,60+i,
      TIMESTAMP '2025-07-15 00:00:00',TIMESTAMP '2026-06-30 23:59:59');
  END LOOP;
END;
/
COMMIT;

-- 4) REGISTRATIONS (Liga 1 & Cupa) + schimbari in sezonul de iarna
DECLARE
  v_l1 NUMBER;
  v_cu NUMBER;
BEGIN
  SELECT competition_id INTO v_l1
  FROM competitions
  WHERE code='L1' AND season='2025/26' AND ROWNUM=1;

  SELECT competition_id INTO v_cu
  FROM competitions
  WHERE code='CUPA' AND season='2025/26' AND ROWNUM=1;

  -- toti -> Liga 1
  FOR r IN (
    SELECT p.player_id, ct.club_id
    FROM players p
    JOIN contracts ct ON ct.player_id = p.player_id
                     AND ct.transaction_end = TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
  ) LOOP
    version_registration(r.player_id, r.club_id, v_l1, 'registered',
                         TIMESTAMP '2025-08-01 00:00:00',
                         TIMESTAMP '2026-06-01 23:59:59');
  END LOOP;

  -- subset (player_id par) -> Cupa
  FOR r IN (
    SELECT p.player_id, ct.club_id
    FROM players p
    JOIN contracts ct ON ct.player_id = p.player_id
                     AND ct.transaction_end = TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
    WHERE MOD(p.player_id,2)=0
  ) LOOP
    version_registration(r.player_id, r.club_id, v_cu, 'registered',
                         TIMESTAMP '2025-09-01 00:00:00',
                         TIMESTAMP '2026-06-01 23:59:59');
  END LOOP;

  -- ~15% schimbări iarnă (deregister + re-register)
  FOR r IN (
    SELECT p.player_id, ct.club_id
    FROM players p
    JOIN contracts ct ON ct.player_id = p.player_id
                     AND ct.transaction_end = TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
    WHERE MOD(p.player_id,7)=0
  ) LOOP
    version_registration(r.player_id, r.club_id, v_l1, 'deregistered',
                         TIMESTAMP '2026-02-01 00:00:00',
                         TIMESTAMP '2026-02-15 00:00:00');
    version_registration(r.player_id, r.club_id, v_l1, 'registered',
                         TIMESTAMP '2026-02-15 00:00:00',
                         TIMESTAMP '2026-06-01 23:59:59');
  END LOOP;
END;
/
COMMIT;

-- 5) MATCHES (Liga: 15 meciuri) + Cupa: 3 meciuri -- 
DECLARE
  v_l1 NUMBER;
  TYPE tclub IS TABLE OF NUMBER;
  clubs6 tclub;
  v_date TIMESTAMP := TIMESTAMP '2025-08-08 20:00:00';
BEGIN
  SELECT competition_id INTO v_l1
  FROM competitions
  WHERE code='L1' AND season='2025/26' AND ROWNUM=1;

  clubs6 := tclub(
    club_id('FCSB'),
    club_id('CFR Cluj'),
    club_id('Rapid București'),
    club_id('Universitatea Craiova'),
    club_id('Farul Constanța'),
    club_id('Dinamo București')
  );

  FOR i IN 1..clubs6.COUNT-1 LOOP
    FOR j IN i+1..clubs6.COUNT LOOP
      INSERT INTO matches(
        competition_id, match_date, home_club_id, away_club_id, venue,
        valid_start, valid_end, transaction_start, transaction_end
      )
      VALUES (
        v_l1, v_date, clubs6(i), clubs6(j), 'Stadium',
        v_date, TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'),
        SYSTIMESTAMP, TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
      );
      v_date := v_date + NUMTODSINTERVAL(7,'DAY');
    END LOOP;
  END LOOP;
END;
/
COMMIT;

DECLARE
  v_cu NUMBER;
  TYPE tpair  IS RECORD(h NUMBER, a NUMBER);
  TYPE tptab  IS TABLE OF tpair;
  pr tptab;
  v_date TIMESTAMP := TIMESTAMP '2025-09-20 18:00:00';
BEGIN
  SELECT competition_id INTO v_cu
  FROM competitions
  WHERE code='CUPA' AND season='2025/26' AND ROWNUM=1;

  pr := tptab(
    tpair(club_id('FCSB'),                 club_id('Dinamo București')),
    tpair(club_id('CFR Cluj'),             club_id('Universitatea Craiova')),
    tpair(club_id('Rapid București'),      club_id('Farul Constanța'))
  );

  FOR i IN 1..pr.COUNT LOOP
    INSERT INTO matches(
      competition_id, match_date, home_club_id, away_club_id, venue,
      valid_start, valid_end, transaction_start, transaction_end
    )
    VALUES (
      v_cu, v_date, pr(i).h, pr(i).a, 'Cup Venue',
      v_date, TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'),
      SYSTIMESTAMP, TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
    );
    v_date := v_date + NUMTODSINTERVAL(3,'DAY');
  END LOOP;
END;
/
COMMIT;

-- 6) APPEARANCES (starters + subs) --
DECLARE
  CURSOR cm IS
    SELECT match_id, home_club_id, away_club_id, match_date
    FROM matches
    ORDER BY match_date, match_id;

  FUNCTION club_players_18(p_club NUMBER) RETURN SYS.ODCINUMBERLIST IS
    v SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST();
  BEGIN
    SELECT player_id BULK COLLECT INTO v
    FROM (
      SELECT p.player_id
      FROM players p
      JOIN contracts ct ON ct.player_id = p.player_id
      WHERE ct.club_id = p_club
        AND ct.transaction_end = TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
      ORDER BY p.player_id
    )
    WHERE ROWNUM <= 18;
    RETURN v;
  END;
BEGIN
  FOR r IN cm LOOP
    DECLARE
      v_home SYS.ODCINUMBERLIST := club_players_18(r.home_club_id);
      v_away SYS.ODCINUMBERLIST := club_players_18(r.away_club_id);
      v_start TIMESTAMP := r.match_date;
    BEGIN
      -- home starters
      FOR i IN 1..LEAST(11, v_home.COUNT) LOOP
        version_appearance(r.match_id, v_home(i), r.home_club_id, 'starter',
                           90, CASE WHEN i<=2 THEN 1 ELSE 0 END, 0, 0, 0,
                           v_start, TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
      END LOOP;
      -- home subs
      FOR i IN 12..LEAST(18, v_home.COUNT) LOOP
        version_appearance(r.match_id, v_home(i), r.home_club_id, 'sub',
                           20, 0, 0, 0, 0,
                           v_start, TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
      END LOOP;

      -- away starters
      FOR i IN 1..LEAST(11, v_away.COUNT) LOOP
        version_appearance(r.match_id, v_away(i), r.away_club_id, 'starter',
                           90, CASE WHEN i=1 THEN 1 ELSE 0 END, 0, 0, 0,
                           v_start, TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
      END LOOP;
      -- away subs
      FOR i IN 12..LEAST(18, v_away.COUNT) LOOP
        version_appearance(r.match_id, v_away(i), r.away_club_id, 'sub',
                           15, 0, 0, 0, 0,
                           v_start, TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
      END LOOP;
    END;
  END LOOP;
END;
/
COMMIT;

-- 7) VERIFICARI --
SELECT
  (SELECT COUNT(*) FROM players)        AS players_cnt,
  (SELECT COUNT(*) FROM clubs)          AS clubs_cnt,
  (SELECT COUNT(*) FROM competitions)   AS competitions_cnt,
  (SELECT COUNT(*) FROM coaches)        AS coaches_cnt,
  (SELECT COUNT(*) FROM club_coaches)   AS club_coaches_cnt,
  (SELECT COUNT(*) FROM registrations)  AS registrations_cnt,
  (SELECT COUNT(*) FROM matches)        AS matches_cnt,
  (SELECT COUNT(*) FROM appearances)    AS appearances_cnt
FROM dual;

SELECT * FROM players FETCH FIRST 10 ROWS ONLY;
