-- Drop VIEW-uri
BEGIN
  FOR v IN (SELECT view_name FROM user_views WHERE view_name IN (
    'V_OPEN_CONTRACTS','V_OPEN_REGISTRATIONS','V_OPEN_APPEARANCES',
    'V_CURRENT_VALID_REGISTRATIONS','V_HEAD_COACH_HISTORY',
    'V_LATE_ENTRIES','V_REGISTRATIONS_ALL_CURRENT','V_REGISTRATIONS_ASOF_BASE',
    'V_CURRENT_DEPARTMENTS_PER_CLUB','V_CURRENT_PLAYER_SQUAD'
  )) LOOP
    EXECUTE IMMEDIATE 'DROP VIEW '||v.view_name;
  END LOOP;
END;
/

-- Drop TRIGGERe
BEGIN
  FOR t IN (SELECT trigger_name FROM user_triggers WHERE trigger_name IN (
    'SET_TX_TIMES_CLUBS','SET_TX_TIMES_COACHES','SET_TX_TIMES_CLUB_COACHES',
    'SET_TX_TIMES_PLAYERS','SET_TX_TIMES_CONTRACTS','SET_TX_TIMES_COMPETITIONS',
    'SET_TX_TIMES_MATCHES','SET_TX_TIMES_REGISTRATIONS','SET_TX_TIMES_APPEARANCES',
    'SET_TX_TIMES_CLUB_DEPARTMENTS','SET_TX_TIMES_COACH_DEPT_ROLES','SET_TX_TIMES_PLAYER_DEPT_ASSIGN',
    'TRG_ENFORCE_U21_STARTERS'
  )) LOOP
    EXECUTE IMMEDIATE 'DROP TRIGGER '||t.trigger_name;
  END LOOP;
END;
/

-- Drop proceduri/functii
BEGIN
  FOR p IN (SELECT object_name, object_type FROM user_objects
            WHERE object_type IN ('PROCEDURE','FUNCTION')
              AND object_name IN ('VERSION_CONTRACT','VERSION_REGISTRATION','VERSION_APPEARANCE','CLUB_ID','COACH_ID_BY_NAME','ADD_PLAYER_WITH_CONTRACT','DEPT_ID','IS_U21_AT')) LOOP
    EXECUTE IMMEDIATE 'DROP '||p.object_type||' '||p.object_name;
  END LOOP;
END;
/

-- Drop tabele
BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
    'APPEARANCES','REGISTRATIONS','MATCHES','COMPETITIONS','CONTRACTS',
    'CLUB_COACHES','COACHES','PLAYERS','CLUBS',
    'PLAYER_DEPARTMENT_ASSIGNMENTS','COACH_DEPARTMENT_ROLES','CLUB_DEPARTMENTS'
  )) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS';
  END LOOP;
END;
/
