ALTER SESSION SET NLS_TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS';

CREATE TABLE club_departments (
  department_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id             NUMBER NOT NULL REFERENCES clubs(club_id),
  name                VARCHAR2(80) NOT NULL,
  valid_start         TIMESTAMP NOT NULL,
  valid_end           TIMESTAMP NOT NULL,
  transaction_start   TIMESTAMP NOT NULL,
  transaction_end     TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end),
  CONSTRAINT uq_club_dept UNIQUE (club_id, name, valid_start)
);

CREATE TABLE coach_department_roles (
  coach_dept_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id       NUMBER NOT NULL REFERENCES club_departments(department_id),
  coach_id            NUMBER NOT NULL REFERENCES coaches(coach_id),
  role                VARCHAR2(80) DEFAULT 'head' NOT NULL,
  valid_start         TIMESTAMP NOT NULL,
  valid_end           TIMESTAMP NOT NULL,
  transaction_start   TIMESTAMP NOT NULL,
  transaction_end     TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end)
);

CREATE TABLE player_department_assignments (
  player_dept_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id           NUMBER NOT NULL REFERENCES players(player_id),
  department_id       NUMBER NOT NULL REFERENCES club_departments(department_id),
  note                VARCHAR2(80), -- ex: 'promoted', 'academy'
  valid_start         TIMESTAMP NOT NULL,
  valid_end           TIMESTAMP NOT NULL,
  transaction_start   TIMESTAMP NOT NULL,
  transaction_end     TIMESTAMP NOT NULL,
  PERIOD FOR valid_period (valid_start, valid_end)
);

-- Triggers pentru transaction_time
CREATE OR REPLACE TRIGGER set_tx_times_club_departments
BEFORE INSERT ON club_departments FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end, TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_coach_dept_roles
BEFORE INSERT ON coach_department_roles FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end, TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

CREATE OR REPLACE TRIGGER set_tx_times_player_dept_assign
BEFORE INSERT ON player_department_assignments FOR EACH ROW
BEGIN
  :NEW.transaction_start := NVL(:NEW.transaction_start, SYSTIMESTAMP);
  :NEW.transaction_end   := NVL(:NEW.transaction_end, TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'));
END;
/

-- Helperi
-- department_id dupa club + nume
CREATE OR REPLACE FUNCTION dept_id(p_club_name VARCHAR2, p_dept_name VARCHAR2)
RETURN NUMBER IS v_id NUMBER;
BEGIN
  SELECT d.department_id INTO v_id
  FROM club_departments d
  WHERE d.club_id = club_id(p_club_name)
    AND d.name    = p_dept_name
    AND ROWNUM=1;
  RETURN v_id;
END;
/

-- 2 departamente per club (Senior, U21)
BEGIN
  FOR r IN (SELECT club_id, name FROM clubs) LOOP
    INSERT INTO club_departments(club_id, name, valid_start, valid_end,
                                 transaction_start, transaction_end)
    VALUES (r.club_id, 'Senior',
            TIMESTAMP '2025-07-15 00:00:00', TO_TIMESTAMP('9999-12-31 23:59:59'),
            SYSTIMESTAMP, TO_TIMESTAMP('9999-12-31 23:59:59'));
    INSERT INTO club_departments(club_id, name, valid_start, valid_end,
                                 transaction_start, transaction_end)
    VALUES (r.club_id, 'U21',
            TIMESTAMP '2025-07-15 00:00:00', TO_TIMESTAMP('9999-12-31 23:59:59'),
            SYSTIMESTAMP, TO_TIMESTAMP('9999-12-31 23:59:59'));
  END LOOP;
END;
/

INSERT INTO coach_department_roles(department_id, coach_id, role,
                                   valid_start, valid_end, transaction_start, transaction_end)
SELECT
  dept.department_id,
  cc.coach_id,
  'head',
  cc.valid_start, cc.valid_end,
  SYSTIMESTAMP, TO_TIMESTAMP('9999-12-31 23:59:59')
FROM club_coaches cc
JOIN clubs c ON c.club_id = cc.club_id
JOIN club_departments dept
  ON dept.club_id = c.club_id AND dept.name = 'Senior'
WHERE cc.role = 'head';

-- repartizarea jucatorilor pe departamente
--    ~75% Senior, ~25% U21
BEGIN
  FOR r IN (
    SELECT p.player_id, ct.club_id
    FROM players p
    JOIN contracts ct
      ON ct.player_id = p.player_id
     AND ct.transaction_end = TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
  ) LOOP
    IF MOD(r.player_id,4)=0 THEN
      -- U21 (~25%)
      INSERT INTO player_department_assignments(player_id, department_id, note,
             valid_start, valid_end, transaction_start, transaction_end)
      VALUES (r.player_id,
              (SELECT department_id FROM club_departments
               WHERE club_id = r.club_id AND name='U21' AND ROWNUM=1),
              'academy',
              TIMESTAMP '2025-07-15 00:00:00', TO_TIMESTAMP('9999-12-31 23:59:59'),
              SYSTIMESTAMP, TO_TIMESTAMP('9999-12-31 23:59:59'));
    ELSE
      -- Senior (~75%)
      INSERT INTO player_department_assignments(player_id, department_id, note,
             valid_start, valid_end, transaction_start, transaction_end)
      VALUES (r.player_id,
              (SELECT department_id FROM club_departments
               WHERE club_id = r.club_id AND name='Senior' AND ROWNUM=1),
              'first-team',
              TIMESTAMP '2025-07-15 00:00:00', TO_TIMESTAMP('9999-12-31 23:59:59'),
              SYSTIMESTAMP, TO_TIMESTAMP('9999-12-31 23:59:59'));
    END IF;
  END LOOP;
END;
/

-- View-uri
-- Departamente curente pe club (inclusiv head coach)
CREATE OR REPLACE VIEW v_current_departments_per_club AS
SELECT c.name AS club_name, d.name AS department_name,
       ch.full_name AS head_coach,
       d.valid_start, d.valid_end
FROM club_departments d
JOIN clubs c ON c.club_id = d.club_id
LEFT JOIN coach_department_roles cdr
       ON cdr.department_id = d.department_id
      AND cdr.role='head'
      AND cdr.valid_start <= SYSTIMESTAMP
      AND cdr.valid_end   >  SYSTIMESTAMP
LEFT JOIN coaches ch ON ch.coach_id = cdr.coach_id
WHERE d.valid_start <= SYSTIMESTAMP
  AND d.valid_end   >  SYSTIMESTAMP
  AND d.transaction_end = TO_TIMESTAMP('9999-12-31 23:59:59');

-- Lotul curent (Senior/U21) pentru fiecare jucator
CREATE OR REPLACE VIEW v_current_player_squad AS
SELECT p.full_name, cl.name AS club_name, d.name AS department_name, a.note,
       a.valid_start, a.valid_end
FROM player_department_assignments a
JOIN players p ON p.player_id = a.player_id
JOIN club_departments d ON d.department_id = a.department_id
JOIN clubs cl ON cl.club_id = d.club_id
WHERE a.valid_start <= SYSTIMESTAMP
  AND a.valid_end   >  SYSTIMESTAMP
  AND a.transaction_end = TO_TIMESTAMP('9999-12-31 23:59:59');

SELECT
  (SELECT COUNT(*) FROM club_departments)            AS dept_cnt,
  (SELECT COUNT(*) FROM coach_department_roles)      AS coach_dept_cnt,
  (SELECT COUNT(*) FROM player_department_assignments) AS player_dept_cnt
FROM dual;
